require("settings")
require("plugins")
require("mappings")

require("telescope-config")
require("treesitter-config")
require("harpoon-config")
require("yanky-config")
require("gitsigns-config")
require("treesitter-context-config")
require("nvim-lastplace-config")
require("autosave-config")
require("spectre-config")
require("lsp-conf")
require("cmp-config")
require("diagnostic-config")
require("lualine_config")
require("lsp-lines-config")
require("live_command_config")
require("crates_config")

require("colors")
