require("settings")
require("plugins")
require("mappings")

require("telescope-config")
require("treesitter-config")
require("harpoon-config")
require("yanky-config")
require("gitsigns-config")
require("treesitter-context-config")
require("nvim-lastplace-config")
require("autosave-config")
require("spectre-config")
require("lsp-conf")
require("cmp-config")

require("colors")
