-- vim.cmd("colorscheme melange")
-- vim.cmd("highlight! Normal guibg=#221E1A")
-- vim.cmd("highlight! link LineNr StatusLine")
-- vim.cmd("highlight! GitSignsAdd guibg=#352f2a")
-- vim.cmd("highlight! GitSignsChange guibg=#352f2a")
-- vim.cmd("highlight! GitSignsDelete guibg=#352f2a")
-- vim.cmd("highlight! CursorLineNr guibg=#352f2a")
-- vim.cmd("highlight! WinBar guibg=#352f2a")
require('github-theme').setup({
    theme_style = "dark_default",
    dark_float = "true",
})
vim.cmd("highlight! @variable guifg=#c9d1d9")
-- vim.cmd("highlight! @namespace guifg=#ffa657")
vim.cmd("highlight! @type guifg=#79c0ff")
-- vim.cmd("highlight! @punctuation.delimiter guifg=#ff7b72")
vim.cmd("highlight! link @punctuation.delimiter @variable")
vim.cmd("highlight! link @punctuation.special @variable")
vim.cmd("highlight! link @punctuation.bracket @variable")
vim.cmd("highlight! @function.macro gui=bold guifg=#d2a8ff")
vim.cmd("highlight! DiffText gui=bold guifg=#341a00 guibg=#e3b341")
-- vim.cmd("highlight! @string guifg=#56d364")
-- vim.cmd("colorscheme modus-operandi")
