vim.cmd("colorscheme mine-shaft")
vim.cmd("highlight! link GlanceNone Search")
vim.cmd("highlight! link GlanceWinBarFilename Visual")
vim.cmd("highlight! link GlanceWinBarFilepath Visual")
vim.cmd("highlight! link GlanceWinBarTitle Visual")
vim.cmd("highlight! GlancePreviewMatch guifg=#000000 guibg=#ffff00")
vim.cmd("highlight! Debug guifg=#00ff00 guibg=#ff00ff")
vim.cmd("highlight! GlanceListCursorLine guibg=#1B1B1B")
vim.cmd("highlight! GlancePreviewCursorLine guibg=#1B1B1B")
vim.cmd("highlight! GlancePreviewLineNr guibg=#1B1B1B")
-- vim.cmd("colorscheme modus-operandi")
